chart-dirs:
  - charts
target-branch: main
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - bitnami=https://tianping526.github.io/charts
  - tianping526=https://tianping526.github.io/helm-charts
