apiVersion: v2
appVersion: 5.3.4
description: A Helm chart for deploying a RocketMQ cluster
keywords:
- rocketmq
- kubernetes
- apache
maintainers:
  - name: tianping526
    email: 1553260215@qq.com
name: rocketmq
type: application
version: 5.5.0
